### ISSUE TITLE
Proposal: Separate base cadmium repo into multiple smaller repos

### ISSUE THREAD

**Issue by watzon** [cadmiumcr/rfcs#1]
## Preface

Currently [the base repo](https://github.com/cadmiumcr/cadmium) is somewhat of a monolithic project. I would like it to be separated into multiple smaller repos so that only the necessary pieces can be included.

## Details

The idea behind creating an org is to have cadmium separated into multiple smaller pieces. This will allow people to pick and choose the pieces of cadmium that they want to include in their projects, allow pieces to be added to cadmium easier, separate issue tracking for different pieces, and will allow the project to grow more readily than it could otherwise.

This should probably be done in stages with one piece at a time being migrated to its own repository. Help will be much appreciated, so feel free to comment if there is a specific piece you want to handle.

#### Todo

- [x] Tokenizers
- [x] String Distance
- [x] Stemmers
- [x] Classifiers
- [x] Phonetics
- [x] Inflectors
- [x] N-Grams
- [x] TF-IDF
- [x] Transliterator
- [x] Sentiment Analysis
- [x] Tries
- [x] EdgeWeightedDigraph
- [x] [Readability](/cadmiumcr/readability)
- [x] [Wordnet](/cadmiumcr/wordnet)
- [x] Utils

**Comment by rmarronnier** [comment]
I'll create the summarizers repo and move the code there.
Also will do the i18n unless you beat me to it.

**Comment by watzon** [comment]
> I'll create the summarizers repo and move the code there.
> Also will do the i18n unless you beat me to it.

Sounds good, I was going to start on i18n, but I think I'm gonna work on a website instead. I'm conflicted about whether to have i18n be its own thing or be a part of `Cadmium::Util`. I kind of like the idea of having all utility stuff like that as a part of `Cadmium::Util`.

**Comment by rmarronnier** [comment]
ok, then let's make it `Cadmium::Util::i18n`. I'll start on it tomorrow (I want to finish my language detector thing before )

**Comment by rmarronnier** [comment]
Could you create the stemmer repo ? You don't have to have it working, I'll fork it and the tokenizer one, make them working (testing with the summarizer module) and make you PRs when it's ready :-)

**Comment by rmarronnier** [comment]
Thanks but it's empty... So I can't fork it :-/ just `crystal init lib stemmer`, push it to cadmiumcr/stemmer and I'll take it from there. (the reason I don't directly create the repo, is I don't want the direct write permission to it - ie you'll be the maintainer ;-))

**Comment by rmarronnier** [comment]
Nice ! :-D

**Comment by rmarronnier** [comment]
Guess what, we forgot one little part of Cadmium... the `core_ext` of course ! I'll give you time to decide what to do about this folder, because I have no idea :-p (igiving it its own repo seems overkill tbh)

**Comment by rmarronnier** [comment]
PR waiting for `cadmium_sentiment`

You can push `tfidf` and I'll take care of it (and be done with migrating for this week :-p)

**Comment by rmarronnier** [comment]
ok, it gets easier with practice, so you can push `EdgeWeightedDigraph`, `Tries` and `Transliterator`. I'll do them.

**Comment by rmarronnier** [comment]
Let's get this over with. Unless you want to handle some specific one, just push all the remaining one live and I'll do them in a swoop.

**Comment by watzon** [comment]
@rmarronnier all repos have been created, with the exception of edge weighted digraph all of them have the name you'd be expecting. In the case of edge weighted digraph I decided to create a `graphs` repo so that we can implement other types of graph as well and have them all grouped together.

**Comment by rmarronnier** [comment]
@watzon : `where is n-grams ` ? I knew it was too easy :-p

**Comment by watzon** [comment]
So weird, I guess I found a bug in github accidentally. I had created ngrams and even pushed to it, but the repo wouldn't show up. Anyway, I created another https://github.com/cadmiumcr/ngrams

**Comment by rmarronnier** [comment]
@watzon `ngrams` done.

So is `cadmiumcr/cadmium` gonna become a Readme and a meta shard of all modules ?
Or something else ?

**Comment by watzon** [comment]
That is the plan for now. `cadmium` will exist as the main entry point and will import every other shard just in case someone wants the whole shebang.
